import { Work_Sans } from 'next/font/google'
import './globals.scss'

const workSans = Work_Sans({ subsets: ['latin'] })

// components
import Header from '@/components/Header'
import Footer from '@/components/Footer'

export const metadata = {
	title: 'Difinery',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={workSans.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
