import { Work_Sans } from 'next/font/google'
import './globals.scss'

const workSans = Work_Sans({ subsets: ['latin'] })

// components
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Cart from '@/components/Cart'

// lib
import { getEntries } from '@/lib/contentful'

// context
import { CartProvider } from '@/context/CartContext'

const header = await getEntries('header')
const footer = await getEntries('footer')

export const metadata = {
	title: 'Difinery',
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.svg'
	}
}

export default function RootLayout({ children }) {
	// Header
	const headerContent = header.items[0].fields
	const footerContent = footer.items[0].fields

	return (
		<html lang='en'>
			<head>
				<link rel='icon' href='/favicon.svg' type='image/svg+xml' />
			</head>
			<CartProvider>
				<body className={workSans.className}>
					<Cart />
					<Header
						mainMenu={headerContent.mainMenu}
						supportPage={headerContent.supportPage}
					/>
					{children}
					<Footer content={footerContent} />
				</body>
			</CartProvider>
		</html>
	)
}
