import { Work_Sans } from 'next/font/google'
import './globals.scss'

const workSans = Work_Sans({ subsets: ['latin'] })

// components
import Header from '@/components/Header'
import Footer from '@/components/Footer'

// lib
import { getEntries } from '@/lib/contentful'

const header = await getEntries('header')
const footer = await getEntries('footer')

export const metadata = {
	title: 'Difinery',
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.svg'
	}
}

export default function RootLayout({ children }) {
	// Header
	const headerContent = header.items[0].fields
	const footerContent = footer.items[0].fields

	return (
		<html lang='en'>
			<head>
				<link rel='icon' href='/favicon.svg' type='image/svg+xml' />
			</head>
			<body className={workSans.className}>
				<Header
					mainMenu={headerContent.mainMenu}
					supportPage={headerContent.supportPage}
				/>
				{children}
				<Footer content={footerContent} />
			</body>
		</html>
	)
}
